<xsl:stylesheet version="2.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output omit-xml-declaration="yes" indent="yes"/>
    <xsl:strip-space elements="*"/>

    <xsl:template match="node()|@*">   	<xsl:copy>           		<xsl:apply-templates select="node()|@*"/>	</xsl:copy>   	</xsl:template>

    <xsl:template match="MEINH">        <productnumber>	<xsl:value-of select="."/>	</productnumber>    	</xsl:template>
    <xsl:template match="UMREZ">        <UMREZwasbeforenowchanged>	<xsl:value-of select="."/>	</UMREZwasbeforenowchanged>    	</xsl:template>
    <xsl:template match="UMREN">        <UMRENwasbeforenowchanged>	<xsl:value-of select="."/>	</UMRENwasbeforenowchanged>    	</xsl:template>
    <xsl:template match="LAENG">        <LAENGwasbeforenowchanged>	<xsl:value-of select="."/>	</LAENGwasbeforenowchanged>    	</xsl:template>
    <xsl:template match="BREIT">        <BREITDocumentNumber>		<xsl:value-of select="."/>	</BREITDocumentNumber>    	</xsl:template>


	<xsl:template match="ABTNR|ADDIFM|ADDIFM_TXT|ADDIINHAL|ADDIINHBR|ADDIINHME|ADDIMAKTX|ADDIMATKL|
	ADDIMATKL_TXT|ADDIMATNR|ADDIMATNR_EXTERNAL|ADDIMATNR_GUID|ADDIMATNR_LONG|ADDIMATNR_VERSION|		
	ADDIREL|ADDITXT|ADDIVPREH|AENTP|AKART|AKLIZ|AKTHE|AKTIO|AKTNR|AKTYP|AL_BOM_MATNR|	
	AL_BOM_MATNR_LONG|AL_BOM_MATNR_VERSION|AL_BOM_QUANT|AL_BOM_UNIT|AL_EMP_MATNR|AL_EMP_MATNR_EXTERNAL|
	AL_EMP_MATNR_VERSION|AL_EMP_QUANT|AL_EMP_UNIT|ARANZ|ARCKEY|ASORT|ATTYP|AUFME|AUSDT|AUSME|BASME|BBTYP|BRGEW|
	BSTMA|BWSCL|BWTAR|BWTTY|BWVOR|C_INFO_02|C_INFO_03|C_INFO_04|C_INFO_09|C_INFO_10|C_INFO_12|
	COND_VALUE|CREDAT|CRETIM|CURCY|DATAB|DATBI|DEINK|DIRECT|DISMM|DISPR|DOCNUM|DOCREL|DYN_REDUC|EAN11|EANTP|
	EDI_DC40|EISBE|EKGRP|ETIME|EXPRSS|FACIN|FBDAT|FLDAT|FVERW|GEWEI|HIER_ID|HOEHE|HPEAN|HPLGR|
	IDOCTYP|IPRKZ|KPEIN|KSATZ|KSCHL|KWERT|KZAUSME|KZBSTME|LAEDA|LAISO_ME|LANG_ISO|LAYGR|LAYVR|LFDNR_ME|LFRHY|
	LGRAD|LI_PROC_ST|LIFAB|LIFBI|LIQDT|LIZYK|LMVAR|LMVER|LNGLV|LOCLB|LSTAB|LSTBI|LSTFL|LTSNR|LTSSF|
	MAABC|MABST|MAKTM|MAKTM_ME|MANDT|MARA_BSTME|MARA_INHME|MARA_VABME|MATKL|MATNR_LONG|MAXB|
	MEABM|EINS|MELAY|MESCOD|MESFCT|MESTYP|MHDHB|MHDLP|MHDRZ|MIABG|MINBE|MINBM|MLGUT|MSTDE|MSTDV|
	MTART|MTXID|MTXID_ME|MWSKZ|NDISP|NFMAT|NFMAT_EXTERNAL|NFMAT_GUID|NFMAT_LONG|NFMAT_VERSION|NODE|
	NORBM|NTGEW|OUTMOD|PFLKS|PHFIL|PLGTP|PLTYP_P|PMATN|PMATN_EXTERNAL|PMATN_GUID|PMATN_LONG|PMATN_VERSION|
	PR_REF_MAT|PR_REF_MAT_EXTERNAL|PR_REF_MAT_GUID|PR_REF_MAT_LONG|PR_REF_MAT_VERSION|PRABE|PRDHA|PRDRU|PRE_VENDOR|PRERF|
	PRICE_BAND|PRIMW|PROM_TYPE|PRWOG|PRWUG|RACKJOB|RBZUL|RCVLAD|RCVPFC|RCVPOR|RCVPRN|RCVPRT|RCVSAD|REFGRP|REFINT|REFMES|RELIF|
	RGART|RUECK|SAISJ|SAISO|SATNR_EXTERNAL|SATNR_GUID|SATNR_LONG|SATNR_VERSION|SBDAT|SCABAS_QUAN|SCABAS_VAL|SCALE_TYPE|SEG_REPEAT|
	SERIAL|SERVV|SHELF|SIGN|ADDINUMBER|SLDAT|SKTOF|SNDLAD|SNDPFC|SNDPOR|SNDPRN|SNDPRT|SNDSAD|SOBST|SORF1|SPRAS_ME|
	SSTUF|STATUS|STD|STDMES|ADDINUM_TXT|STDVRS|STIME|STOCK_COUNT|TABNAM|TEST|TRCOV|UEBTO|UNTTO|VABME|
	VERAB|VERBI|VERNR|VKDAB|ADDINUM|VKDAB_A|VKDBI|VKDBI_A|VOLEH|VOLUM|VORZN|VRKME|WAUFT|WREPL|WSTOR|XMCNG|
	AL_BOM_MATNR_EXTERNAL|AL_BOM_MATNR_GUID|AL_EMP_MATNR_GUID|AL_EMP_MATNR_LONG|C_INFO_13|C_INFO_18|C_INFO_20|CIMTYP"/>


</xsl:stylesheet>
